# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install -g nativescript
    npm install
    tns build android --bundle --env.uglify --env.aot --release --key-store-path "/home/vsts/work/1/s/release.keystore" --key-store-password sanjuldgr8 --key-store-alias thoughtskeystore --key-store-alias-password sanjuldgr8 --aab
  displayName: 'npm install and native script setup'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'hope app connection'
    appSlug: 'sanjul.lalwani/Hope'
    appFile: '/home/vsts/work/1/s/platforms/android/app/build/outputs/apk/debug/app-debug.apk'
    buildVersion: '1.0.0'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'New build'
    destinationType: 'groups'
    distributionGroupId: 'beta tester'